name: Generate 3D Contribution Scene

on:
  schedule:
    - cron: "0 */12 * * *" 
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          OUTPUT_PATHS: |
            profile-3d-contrib/profile-green-isometric.svg
            profile-3d-contrib/profile-green-isometric-dark.svg
            profile-3d-contrib/profile-night-view.svg
            profile-3d-contrib/profile-night-green.svg

      - name: Commit & Push changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "generated 3D contribution scene"
          git push
